param(
    [Parameter(Mandatory=$false)]
    [string]$Domain,
    
    [Parameter(Mandatory=$false)]
    [switch]$Help
)

function Generate-Secret {
    $bytes = New-Object Byte[] 32
    (New-Object Security.Cryptography.RNGCryptoServiceProvider).GetBytes($bytes)
    -join ($bytes | ForEach-Object { "{0:x2}" -f $_ })
}

function Show-Help {
    Write-Host "Development Environment Setup Script"
    Write-Host ""
    Write-Host "USAGE:"
    Write-Host "  .\setup.ps1 -Domain <domain> [-Help]"
    Write-Host ""
    Write-Host "OPTIONS:"
    Write-Host "  -Domain <domain>     Project domain (required)"
    Write-Host "  -Help              Show this help message"
    Write-Host ""
    Write-Host "EXAMPLES:"
    Write-Host "  .\setup.ps1 -Domain altrp.localhost"
}

if ($Help) {
    Show-Help
    exit 0
}

if (-not $Domain) {
    Write-Host "Error: Project domain is required (-Domain parameter)" -ForegroundColor Red
    Write-Host "Use -Help for help" -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path "..\.env.template")) {
    Write-Host "Error: .env.template file not found in project root!" -ForegroundColor Red
    exit 1
}

if (Test-Path "..\.env") {
    Write-Host "Error: .env file already exists!" -ForegroundColor Red
    Write-Host "To regenerate, remove the existing file first." -ForegroundColor Yellow
    exit 1
}

Write-Host "Generating secure secrets..." -ForegroundColor Green
$POSTGRES_PASSWORD = Generate-Secret
$PAYLOAD_SECRET = Generate-Secret
$N8N_ENCRYPTION_KEY = Generate-Secret
$MASTRA_API_KEY = Generate-Secret

Write-Host "Creating .env file from .env.template..." -ForegroundColor Green

$templateContent = Get-Content "..\.env.template" -Raw

$envContent = $templateContent -replace "PROJECT_DOMAIN=altrp\.localhost", "PROJECT_DOMAIN=$Domain"
$envContent = $envContent -replace "\{GENERATE_POSTGRES_PASSWORD\}", $POSTGRES_PASSWORD
$envContent = $envContent -replace "\{GENERATE_PAYLOAD_SECRET\}", $PAYLOAD_SECRET
$envContent = $envContent -replace "\{GENERATE_N8N_ENCRYPTION_KEY\}", $N8N_ENCRYPTION_KEY
$envContent = $envContent -replace "\{GENERATE_MASTRA_API_KEY\}", $MASTRA_API_KEY
$envContent = $envContent -replace "# --- COPY THIS FILE TO .env AND FILL IN THE VALUES ---", "# --- GENERATED BY setup.ps1 SCRIPT ---"

$envContent | Out-File "..\.env" -Encoding UTF8

Write-Host "✅ .env file created successfully!" -ForegroundColor Green
Write-Host "📁 Location: $(Resolve-Path ..\.env)" -ForegroundColor Yellow
Write-Host "🔐 Generated secure secrets for:" -ForegroundColor Green
Write-Host "   - Database password" -ForegroundColor White
Write-Host "   - Payload CMS secret" -ForegroundColor White
Write-Host "   - N8N encryption key" -ForegroundColor White
Write-Host "   - Mastra API key" -ForegroundColor White
Write-Host ""
Write-Host "🚀 You can now run: docker-compose up -d" -ForegroundColor Green
